server {
	listen 0.0.0.0:8080;
	server_name example.com;

	client_max_body_size 20M;

	error_page 404 errors/404.html;

	root /home/nseon/rendus/Webserv/html;
	index pages/index.html;

	location / {
		cgi .py /usr/bin/python3;
		cgi .php /usr/bin/php-cgi;
		cgi .pl /usr/bin/perl;
		limit_except GET POST DELETE;
		autoindex on;
		upload_store /home/nseon/rendus/Webserv/uploads/;
	}

	location /test {
		return 301 pages/redirect.html;
	}
	
	location /favicon.ico {
		limit_except GET;
		root /home/nseon/rendus/Webserv/html/assets;
	}
}
