server {
    listen 127.0.0.1:8080;                        # Paire interface:port (par défaut 0.0.0.0)
    server_name example.com;

    client_max_body_size 10M;           # Taille max du corps de la requête

    error_page 404 /errors/404.html;    # Pages d'erreur par défaut
    error_page 500 502 /errors/50x.html;

    root /var/www/html;                 # Répertoire racine par défaut
    index index.html;                   # Fichier par défaut

    # Route principale
    location / {
		cgi .py /usr/bin/python3;
	    cgi .php /usr/bin/php-cgi;
        limit_except GET POST;          # Méthodes autorisées
        autoindex on;                   # Active le directory listing
		upload_store /var/www/tmp;		# Dossier spécifique pour l'écriture des fichiers
		return test;
    }

    # Exemple de redirection
    location /old-page {
        return 301 /new-page;
    }	
}

# Deuxième serveur sur un port différent
server {
    listen 127.0.0.1:9090;
    server_name test.local;
    root /var/www/test;
}
