server {
    listen 127.0.0.1:8080;
    server_name cgi.test;
    client_max_body_size 10000000;
    root /home/lcesbron/Documents/projects/Webserv/cgi;
    index index.html;
    location / {
        cgi .py /usr/bin/python3;
        limit_except GET POST;
    }
}
